# http://conda.pydata.org/docs/travis.html
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.4"
  - "3.5"
  - "3.6"
  - "2"  # Dummy: Run Python 3.6 without any soft dependency
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Take care of dummy version for test without soft dependencies
  - if [ ${TRAVIS_PYTHON_VERSION} == "2" ]; then
      TRAVIS_PYTHON_VERSION="3.6";
      SOFT_DEP="";
    else
      SOFT_DEP="numexpr";
    fi

  # Install and activate environment, install packages
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy pytest pytest-cov $SOFT_DEP
  - source activate test-environment
  - pip install coveralls pytest-flake8
  - python setup.py install


script: pytest --cov=empymod --flake8

after_success: coveralls
